export const navIcons = [
  {
    nav: "Smart Home",
    name: "Smart Home",
    route: "smartHome",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Smart Home",
    name: "Technique",
    route: "technique",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Solutions",
    name: "Hub",
    route: "hub",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Solutions",
    name: "Light",
    route: "light",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Solutions",
    name: "Blinds",
    route: "blinds",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Solutions",
    name: "Environment",
    route: "environment",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Solutions",
    name: "Connection",
    route: "connection",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "Solutions",
    name: "Safety",
    route: "safety",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "About",
    name: "About",
    route: "about",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "About",
    name: "Service",
    route: "service",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "About",
    name: "Cooperation",
    route: "cooperation",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "User",
    name: "User",
    route: "user/account",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "User",
    name: "Cart",
    route: "user/cart",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    nav: "User",
    name: "Order",
    route: "user/order",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
];

export const contentIcons = [
  {
    name: "Chevron Up",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Chevron Down",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Chevron Left",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Chevron Right",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Mode",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Plan",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Install",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Config",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Switch",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Application",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Cost",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Power Consumption",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Expanable",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Nodes",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Stable",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Motion",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
];

export const socialApps = [
  {
    name: "What's App",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Twitter",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Telegram",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Line",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Facebook",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
];
