export const navIcons = [
  {
    label: "Smart Home",
    name: "Smart Home",
    route: "smartHome/smartHome",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Smart Home",
    name: "Technique",
    route: "smartHome/technique",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Solutions",
    name: "Hub",
    route: "solutions/hub",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Solutions",
    name: "Light",
    route: "solutions/light",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Solutions",
    name: "Blinds",
    route: "solutions/blinds",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Solutions",
    name: "Temp. & Hum.",
    route: "solutions/environment",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Solutions",
    name: "Connection",
    route: "solutions/connection",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "Solutions",
    name: "Camera",
    route: "solutions/safety",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "About",
    name: "Logo",
    route: "about/about",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "About",
    name: "Service",
    route: "about/service",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "About",
    name: "Business",
    route: "about/cooperation",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "User",
    name: "User",
    route: "user/account",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "User",
    name: "Cart",
    route: "user/cart",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    label: "User",
    name: "Order",
    route: "user/order",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
];

export const contentIcons = [
  {
    name: "Chevron Up",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Chevron Down",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Chevron Left",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Chevron Right",
    viewbox: "",
    size: 18,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Mode",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Plan",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Install",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Config",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Switch",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Application",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Cost",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Power Consumption",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Expanable",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Nodes",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Stable",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Motion",
    viewbox: "",
    size: 22,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
];

export const socialApps = [
  {
    name: "What's App",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Twitter",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Telegram",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Line",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
  {
    name: "Facebook",
    viewbox: "",
    size: 48,
    stroke: "",
    strokeWidth: 4,
    fill: "",
    path: "",
  },
];
